<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <IsPackable>false</IsPackable>
    <Nullable>disable</Nullable>
    <AssemblyName>PlaySafe.Math.Tests</AssemblyName>
    <RootNamespace>_DL.PlaySafe.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.6.0" />
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="../../Runtime/PlaySafeRecordingDecision.cs" Link="src/PlaySafeRecordingDecision.cs" />
  </ItemGroup>
</Project>
